// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/o-nama": {
    params: {};
  };
  "/usluge": {
    params: {};
  };
  "/galerija": {
    params: {};
  };
  "/kontakt": {
    params: {};
  };
  "/dj-za-korporativni-dogadaj": {
    params: {};
  };
  "/dj-za-proslave": {
    params: {};
  };
  "/dj-za-vjencanja": {
    params: {};
  };
  "/politika-privatnosti": {
    params: {};
  };
  "/uvjeti-koristenja": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/kako-odabrati-dj-a-za-vjencanje": {
    params: {};
  };
  "/blog/najbolja-glazba-za-evente": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/o-nama" | "/usluge" | "/galerija" | "/kontakt" | "/dj-za-korporativni-dogadaj" | "/dj-za-proslave" | "/dj-za-vjencanja" | "/politika-privatnosti" | "/uvjeti-koristenja" | "/blog" | "/blog/kako-odabrati-dj-a-za-vjencanje" | "/blog/najbolja-glazba-za-evente";
  };
  "home/Home.tsx": {
    id: "home/Home";
    page: "/";
  };
  "about/About.tsx": {
    id: "about/About";
    page: "/o-nama";
  };
  "services/Services.tsx": {
    id: "services/Services";
    page: "/usluge";
  };
  "gallery/Gallery.tsx": {
    id: "gallery/Gallery";
    page: "/galerija";
  };
  "contact/Contact.tsx": {
    id: "contact/Contact";
    page: "/kontakt";
  };
  "event-dj/EventDJ.tsx": {
    id: "event-dj/EventDJ";
    page: "/dj-za-korporativni-dogadaj";
  };
  "celebration-dj/CelebrationDJ.tsx": {
    id: "celebration-dj/CelebrationDJ";
    page: "/dj-za-proslave";
  };
  "wedding-dj/WeddingDJ.tsx": {
    id: "wedding-dj/WeddingDJ";
    page: "/dj-za-vjencanja";
  };
  "legal/PrivacyPolicy.tsx": {
    id: "legal/PrivacyPolicy";
    page: "/politika-privatnosti";
  };
  "legal/TermsOfUse.tsx": {
    id: "legal/TermsOfUse";
    page: "/uvjeti-koristenja";
  };
  "blog/Blog.tsx": {
    id: "blog/Blog";
    page: "/blog";
  };
  "blog/posts/PostVjencanje.tsx": {
    id: "blog/posts/PostVjencanje";
    page: "/blog/kako-odabrati-dj-a-za-vjencanje";
  };
  "blog/posts/PostEventi.tsx": {
    id: "blog/posts/PostEventi";
    page: "/blog/najbolja-glazba-za-evente";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "home/Home": typeof import("./src/app/home/Home.tsx");
  "about/About": typeof import("./src/app/about/About.tsx");
  "services/Services": typeof import("./src/app/services/Services.tsx");
  "gallery/Gallery": typeof import("./src/app/gallery/Gallery.tsx");
  "contact/Contact": typeof import("./src/app/contact/Contact.tsx");
  "event-dj/EventDJ": typeof import("./src/app/event-dj/EventDJ.tsx");
  "celebration-dj/CelebrationDJ": typeof import("./src/app/celebration-dj/CelebrationDJ.tsx");
  "wedding-dj/WeddingDJ": typeof import("./src/app/wedding-dj/WeddingDJ.tsx");
  "legal/PrivacyPolicy": typeof import("./src/app/legal/PrivacyPolicy.tsx");
  "legal/TermsOfUse": typeof import("./src/app/legal/TermsOfUse.tsx");
  "blog/Blog": typeof import("./src/app/blog/Blog.tsx");
  "blog/posts/PostVjencanje": typeof import("./src/app/blog/posts/PostVjencanje.tsx");
  "blog/posts/PostEventi": typeof import("./src/app/blog/posts/PostEventi.tsx");
};